import {auth,db,googleProvider,signInWithPopup,signInWithEmailAndPassword,createUserWithEmailAndPassword,signOut,onAuthStateChanged,updateProfile,sendPasswordResetEmail,collection,doc,setDoc,deleteDoc,getDoc,onSnapshot} from './firebase-app.js';
const $=id=>document.getElementById(id);let members=[],editing=null,uid=null,unsubscribe=null;
const money=n=>'₹'+Number(n||0).toLocaleString('en-IN');
function show(id,on=true){$(id).classList.toggle('hidden',!on)}
function avatar(m){return m.photo?`<img class="memberAvatar" src="${m.photo}" alt="${m.name}">`:'<span class="memberAvatar placeholder">👤</span>'}
function render(){
  $('totalMembers').textContent=members.length;
  $('activeMembers').textContent=members.filter(m=>m.status==='Active').length;
  $('collectedFees').textContent=money(members.reduce((s,m)=>s+Number(m.paid||0),0));
  $('pendingFees').textContent=money(members.reduce((s,m)=>s+Math.max(0,Number(m.fee||0)-Number(m.paid||0)),0));
  const q=$('search').value.toLowerCase();
  const list=members.filter(m=>(m.name+' '+m.phone).toLowerCase().includes(q));
  const row=m=>`<tr><td>${m.name}</td><td>${m.phone}</td><td>${m.joiningDate}</td><td>${money(m.fee)}</td><td>${m.dueMonth||'-'}</td><td>${m.status}</td><td><button class="action" onclick="viewMember('${m.id}')">View</button><button class="action" onclick="editMember('${m.id}')">Edit</button><button class="action" onclick="deleteMember('${m.id}')">Delete</button></td></tr>`;
  $('memberRows').innerHTML=list.map(m=>`<tr><td><span class="memberName">${avatar(m)}<b>${m.name}</b></span></td><td>${m.phone}</td><td>${m.joiningDate}</td><td>${money(m.fee)}</td><td>${m.dueMonth||'-'}</td><td>${m.status}</td><td><button class="action" onclick="viewMember('${m.id}')">View</button><button class="action" onclick="editMember('${m.id}')">Edit</button><button class="action" onclick="deleteMember('${m.id}')">Delete</button></td></tr>`).join('')||'<tr><td colspan="7">No members found.</td></tr>';
  $('memberRows2').innerHTML=members.map(row).join('')||'<tr><td colspan="7">No members found.</td></tr>';
  $('paymentRows').innerHTML=members.map(m=>`<tr><td>${m.name}</td><td>${money(m.fee)}</td><td>${money(m.paid)}</td><td>${money(Math.max(0,m.fee-m.paid))}</td><td>${m.dueMonth||'-'}</td><td><button class="action" onclick="markPaid('${m.id}')">Mark Paid</button></td></tr>`).join('')||'<tr><td colspan="6">No records.</td></tr>';
  $('recentMembers').innerHTML=members.slice(-5).reverse().map(m=>`<p><b>${m.name}</b> — joined ${m.joiningDate}</p>`).join('')||'<p>No members yet.</p>';
  $('planMember').innerHTML='<option value="">Select member</option>'+members.map(m=>`<option value="${m.id}">${m.name}</option>`).join('');
}
function openModal(m){editing=m||null;$('modalTitle').textContent=m?'Edit Member':'New Member';['memberId','name','phone','email','gender','age','plan','address','joiningDate','fee','paid','dueMonth','status'].forEach(id=>$(id).value='');$('memberId').value=m?.id||'';$('name').value=m?.name||'';$('phone').value=m?.phone||'';$('email').value=m?.email||'';$('gender').value=m?.gender||'';$('age').value=m?.age||'';$('plan').value=m?.plan||'';$('address').value=m?.address||'';$('joiningDate').value=m?.joiningDate||new Date().toISOString().slice(0,10);$('fee').value=m?.fee||'';$('paid').value=m?.paid||0;$('dueMonth').value=m?.dueMonth||'';$('status').value=m?.status||'Active';$('memberPhoto').value='';$('memberPhotoPreview').src=m?.photo||'';$('memberPhotoPreview').classList.toggle('hidden',!m?.photo);$('modal').classList.add('show')}
async function fileToDataUrl(file){return new Promise((resolve,reject)=>{if(!file)return resolve('');const reader=new FileReader();reader.onload=()=>{const img=new Image();img.onload=()=>{const max=220,scale=Math.min(1,max/Math.max(img.width,img.height));const c=document.createElement('canvas');c.width=Math.max(1,Math.round(img.width*scale));c.height=Math.max(1,Math.round(img.height*scale));c.getContext('2d').drawImage(img,0,0,c.width,c.height);resolve(c.toDataURL('image/jpeg',.78))};img.onerror=reject;img.src=reader.result};reader.onerror=reject;reader.readAsDataURL(file)})}
async function saveMember(e){e.preventDefault();const selectedPhoto=await fileToDataUrl($('memberPhoto').files[0]);let m={id:$('memberId').value||crypto.randomUUID(),name:$('name').value,phone:$('phone').value,email:$('email').value,gender:$('gender').value,age:Number($('age').value||0),plan:$('plan').value,address:$('address').value,joiningDate:$('joiningDate').value,fee:Number($('fee').value),paid:Number($('paid').value),dueMonth:$('dueMonth').value,status:$('status').value,photo:selectedPhoto||editing?.photo||'',diet:editing?.diet||'',workout:editing?.workout||''};await setDoc(doc(collection(db,'users',uid,'members'),m.id),m);$('modal').classList.remove('show')}
function safe(v){return String(v??'-').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]))}
window.viewMember=id=>{const m=members.find(x=>x.id===id);if(!m)return;const due=Math.max(0,Number(m.fee||0)-Number(m.paid||0));$('viewTitle').textContent=m.name+' — Member Details';$('viewContent').innerHTML=`<div class="viewTop">${avatar(m)}<div><h3>${safe(m.name)}</h3><p>${safe(m.phone)}</p></div></div><div class="detailGrid"><div><b>Member Information</b><p><strong>Name:</strong> ${safe(m.name)}</p><p><strong>Phone:</strong> ${safe(m.phone)}</p><p><strong>Email:</strong> ${safe(m.email||'-')}</p><p><strong>Gender:</strong> ${safe(m.gender||'-')}</p><p><strong>Age:</strong> ${safe(m.age||'-')}</p><p><strong>Plan:</strong> ${safe(m.plan||'-')}</p><p><strong>Address:</strong> ${safe(m.address||'-')}</p><p><strong>Joining Date:</strong> ${safe(m.joiningDate)}</p><p><strong>Status:</strong> ${safe(m.status)}</p></div><div><b>Fees History</b><p><strong>Monthly Fee:</strong> ${money(m.fee)}</p><p><strong>Paid Fees:</strong> ${money(m.paid)}</p><p><strong>Due Amount:</strong> ${money(due)}</p><p><strong>Due Month:</strong> ${safe(m.dueMonth||'-')}</p></div><div><b>Diet Chart</b><p class="pre">${safe(m.diet||'No diet chart added yet.')}</p></div><div><b>Workout Chart</b><p class="pre">${safe(m.workout||'No workout chart added yet.')}</p></div></div><div class="viewActions"><button class="gold primary" onclick="editMember('${m.id}');closeView()">Edit Member</button><button class="action" onclick="closeView()">Close</button></div>`;$('viewModal').classList.add('show')};window.closeView=()=> $('viewModal').classList.remove('show');
window.editMember=id=>openModal(members.find(m=>m.id===id));window.deleteMember=async id=>{if(confirm('Delete this member?'))await deleteDoc(doc(db,'users',uid,'members',id))};window.markPaid=async id=>{let m=members.find(m=>m.id===id);await setDoc(doc(db,'users',uid,'members',id),{...m,paid:m.fee,dueMonth:'Paid'})};
$('memberForm').onsubmit=saveMember;$('quickAdd').onclick=$('addMember').onclick=()=>openModal();
$('editProfile').onclick=async()=>{const fallback=auth.currentUser?.displayName||((auth.currentUser?.email||'User').split('@')[0]);$('profileName').value=fallback;$('profilePhone').value='';$('profileMsg').textContent='';$('profileModal').classList.add('show');try{const snap=await getDoc(doc(db,'users',uid,'profile','main'));if(snap.exists()){const profile=snap.data();$('profileName').value=profile.name||fallback;$('profilePhone').value=profile.phone||'';}}catch(err){console.warn('Profile read failed:',err);$('profileMsg').textContent='You can still edit and save your profile.';}};
$('closeProfile').onclick=()=>$('profileModal').classList.remove('show');
$('profileForm').onsubmit=async e=>{e.preventDefault();const name=$('profileName').value.trim();const phone=$('profilePhone').value.trim();if(!name)return;$('profileMsg').textContent='Saving...';try{await updateProfile(auth.currentUser,{displayName:name});await setDoc(doc(db,'users',uid,'profile','main'),{name,phone,email:auth.currentUser.email||''},{merge:true});$('profileMsg').textContent='Profile saved successfully';}catch(err){console.error(err);$('profileMsg').textContent='Name updated locally. Firestore setup/rules need checking.';}$('userName').textContent=name;$('heroName').textContent=name;$('welcomeLine').textContent=`Welcome back, ${name}! Manage members, fees and fitness plans.`;};$('closeModal').onclick=()=>$('modal').classList.remove('show');$('search').oninput=render;$('logout').onclick=()=>signOut(auth);document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tab').forEach(t=>t.classList.remove('active'));$(b.dataset.tab).classList.add('active');$('pageTitle').textContent=b.textContent});$('planMember').onchange=()=>{let m=members.find(x=>x.id===$('planMember').value);$('diet').value=m?.diet||'';$('workout').value=m?.workout||''};$('savePlans').onclick=async()=>{let m=members.find(x=>x.id===$('planMember').value);if(!m)return alert('Select a member');await setDoc(doc(db,'users',uid,'members',m.id),{...m,diet:$('diet').value,workout:$('workout').value});$('planMsg').textContent='Saved'};
$('memberPhoto').onchange=()=>{const f=$('memberPhoto').files[0];if(!f){$('memberPhotoPreview').classList.add('hidden');return}const r=new FileReader();r.onload=()=>{$('memberPhotoPreview').src=r.result;$('memberPhotoPreview').classList.remove('hidden')};r.readAsDataURL(f)};
$('loginForm').onsubmit=async e=>{e.preventDefault();try{await signInWithEmailAndPassword(auth,$('loginEmail').value,$('loginPassword').value)}catch(err){$('authMsg').textContent=err.message}};$('googleLogin').onclick=async()=>{try{await signInWithPopup(auth,googleProvider)}catch(err){$('authMsg').textContent=err.message}};$('signup').onclick=async()=>{try{await createUserWithEmailAndPassword(auth,$('loginEmail').value,$('loginPassword').value)}catch(err){$('authMsg').textContent=err.message}};
onAuthStateChanged(auth,user=>{if(unsubscribe)unsubscribe();if(!user){show('loginScreen',true);show('app',false);return}uid=user.uid;show('loginScreen',false);show('app',true);const displayName=user.displayName||((user.email||'User').split('@')[0]);$('userName').textContent=displayName;$('heroName').textContent=displayName;$('userEmail').textContent=user.email||'Signed in';$('welcomeLine').textContent=`Welcome back, ${displayName}! Manage members, fees and fitness plans.`;unsubscribe=onSnapshot(collection(db,'users',uid,'members'),snap=>{members=snap.docs.map(d=>d.data());render()})});

$('forgotPassword').onclick=async()=>{const email=$('loginEmail').value.trim();if(!email)return $('authMsg').textContent='Enter your email address first.';try{await sendPasswordResetEmail(auth,email);$('authMsg').textContent='Password reset email sent.'}catch(err){$('authMsg').textContent=err.message}};
